FROM goshugh/ksignkms:3_1
USER postgres
ENV PGDATA=/var/lib/postgresql/data
ENV LANG=C
RUN pg_ctl start
USER kms
EXPOSE 5696
RUN cd /home/kms/KSignKMS_v3.2.4/apache-tomcat-9.0.74/bin
CMD ["startup.sh"]
