FROM alpine
RUN apk add postgresql postgresql-client
RUN mkdir /run/postgredsql
RUN chown postgres:postgres /run/postgresql
USER postgres
ENV PGDATA=/tmp/data
ENV LANG=C
RUN initdb -U postgres
USER root

